# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='look',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
