# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20171021_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='mac',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
